# Generated by Django 4.2.10 on 2024-02-12 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comcato', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
