# Generated by Django 4.2.10 on 2024-03-07 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favouritetopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio_files/')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('foreign_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_language_materials', to='authentication.language')),
                ('your_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_language_materials', to='authentication.language')),
            ],
        ),
        migrations.CreateModel(
            name='Userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('firstname', models.TextField(blank=True, null=True)),
                ('lastname', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('Gender', models.TextField(blank=True, null=True)),
                ('Country', models.TextField(blank=True, null=True)),
                ('favourite_topics', models.ManyToManyField(blank=True, to='authentication.favouritetopic')),
                ('interests', models.ManyToManyField(blank=True, to='authentication.interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('your_language', models.ManyToManyField(blank=True, to='authentication.language')),
            ],
        ),
        migrations.RenameModel(
            old_name='payments',
            new_name='Payment',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.DeleteModel(
            name='audiotype',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Userdetails',
        ),
    ]
